id: I894F094E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T13:02:32+00:00'
last_modified: '2022-06-07T18:47:40.937496+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23912
  title: རིགས་དང་དཀྱིལ་འཁོར་རྒྱ་མཚོའི་ཁྱབ་བདག་ཧེ་རུ་ཀཿ་དཔལ་ངུར་སྨྲིག་གར་རོལ་སྐྱབས་གཅིག་ཕ་བོང་ཁ་པ་བདེ་ཆེན་སྙིང་པོ་དཔལ་བཟང་པོའི་རྣམ་པར་ཐར་པ་དོན་ལྡན་ཚངས་པའི་དབྱངས་སྙན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '1623':
      image_group_id: I4556
      title: ''
      total_pages: 594
      order: 1
      base_file: 1623.txt
    '1444':
      image_group_id: I4557
      title: ''
      total_pages: 544
      order: 2
      base_file: 1444.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
