id: opecha:P003275
initial_creation_type: ocr
source_metadata:
  id: bdr:W23912
  title: རིགས་དང་དཀྱིལ་འཁོར་རྒྱ་མཚོའི་ཁྱབ་བདག་ཧེ་རུ་ཀཿ་དཔལ་ངུར་སྨྲིག་གར་རོལ་སྐྱབས་གཅིག་ཕ་བོང་ཁ་པ་བདེ་ཆེན་སྙིང་པོ་དཔལ་བཟང་པོའི་རྣམ་པར་ཐར་པ་དོན་ལྡན་ཚངས་པའི་དབྱངས་སྙན
  volume: ''
  author: ''
