id: P003275
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:51:59.175198
source_metadata:
  id: bdr:W23912
  title: རིགས་དང་དཀྱིལ་འཁོར་རྒྱ་མཚོའི་ཁྱབ་བདག་ཧེ་རུ་ཀཿ་དཔལ་ངུར་སྨྲིག་གར་རོལ་སྐྱབས་གཅིག་ཕ་བོང་ཁ་པ་བདེ་ཆེན་སྙིང་པོ་དཔལ་བཟང་པོའི་རྣམ་པར་ཐར་པ་དོན་ལྡན་ཚངས་པའི་དབྱངས་སྙན
  author: ''
  volumes:
    8e33ac09f7f24cdbb4a8fc0e6e6a551d:
      image_group_id: I4556
      title: ''
      volume_number: 1
      total_pages: 594
      base_file: v001.txt
    0708728c518b4c28b014f646d66dce38:
      image_group_id: I4557
      title: ''
      volume_number: 2
      total_pages: 544
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
